In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
#Import the data into notebook
import os
import pandas as pd
import seaborn as sns
titanic_train_df_v1 = pd.read_csv('/kaggle/input/titanic/train.csv')
tianic_test_df_v1 = pd.read_csv('/kaggle/input/titanic/test.csv')
tianic_gender_df_v1 = pd.read_csv('/kaggle/input/titanic/test.csv')

In [ ]:
#First Step is to clean up data
#Clean the training data-set
print(titanic_train_df_v1.isnull().sum())

In [ ]:
# Replace age with mean value
titanic_train_df_v2 = titanic_train_df_v1.fillna(titanic_train_df_v1.mean())

In [ ]:
#Check if all NaN in age is gone
print(titanic_train_df_v2.isnull().sum())

In [ ]:
#Fix the NaN Cabin numbers
#List all rows which have Cabin number as NaN
titanic_train_df_v3 = titanic_train_df_v2[titanic_train_df_v2.isna().any(axis=1)]
print(titanic_train_df_v3)

In [ ]:
#Looking at complete data-set for Cabin column it is clear that all values are NaN
#So Cabin number column can be dropped off

titanic_train_df_v4 = titanic_train_df_v3.drop(['Cabin'],axis=1)
titanic_train_df_v4.shape

In [ ]:
#Check for any more NaN in the data-set
titanic_train_df_v4.isnull().sum()

In [ ]:
#Embarked has two NaN, these two rows can be dropped off.
#The number of rows will drop from 689 to 687
titanic_train_df_v5 = titanic_train_df_v4[titanic_train_df_v4['Embarked'].notna()]

In [ ]:
titanic_train_df_v5.head

In [ ]:
#Name also can be dropped off
titanic_train_df_v6 = titanic_train_df_v5.drop(['Name'],axis=1)

#Ticket-id can be dropped off
titanic_train_df_v7 = titanic_train_df_v6.drop(['Ticket'],axis=1)

titanic_train_df_v7.head

In [ ]:
#Now convert all categoricals using 1-hot encoding
titanic_train_df_v7.head()

In [ ]:
#Now 1-hot encoding for Sex
one_hot_features = ['Sex']
# Convert categorical variables into dummy/indicator variables (i.e. one-hot encoding).
one_hot_encoded = pd.get_dummies(titanic_train_df_v7[one_hot_features],drop_first=True)
one_hot_encoded.info(verbose=True, memory_usage=True, null_counts=True)
one_hot_encoded.head()

In [ ]:
# Replacing categorical columns with dummies
titanic_train_df_v8 = titanic_train_df_v7.drop(one_hot_features,axis=1)
titanic_train_df_v8 = pd.concat([titanic_train_df_v7, one_hot_encoded] ,axis=1)
titanic_train_df_v8.head()

In [ ]:
titanic_train_df_v9 = titanic_train_df_v8.drop(['Sex'],axis=1)

In [ ]:
titanic_train_df_v9.head()

In [ ]:
#Now 1-hot-encoding for Embarked column
one_hot_features = ['Embarked']
one_hot_encoded = pd.get_dummies(titanic_train_df_v9[one_hot_features],drop_first=True)
one_hot_encoded.head()

In [ ]:
# Replacing categorical columns with dummies
titanic_train_df_v10 = titanic_train_df_v9.drop(one_hot_features,axis=1)
titanic_train_df_v10 = pd.concat([titanic_train_df_v9, one_hot_encoded] ,axis=1)
titanic_train_df_v10.head()

In [ ]:
#Drop the embarked column
titanic_train_df_v11 = titanic_train_df_v10.drop(['Embarked'],axis=1)
titanic_train_df_v11.head()

In [ ]:
#Now make age and Fare and Age normalized.
titanic_train_df_v11['Fare']=(titanic_train_df_v11['Fare']-titanic_train_df_v11['Fare'].mean())/titanic_train_df_v11['Fare'].std()
titanic_train_df_v11['Age']=(titanic_train_df_v11['Age']-titanic_train_df_v11['Age'].mean())/titanic_train_df_v11['Age'].std()

In [ ]:
#Split into X_train and y_train to seperate dependent and indepdent variable

titanic_train_df_v12_X_train = titanic_train_df_v11.drop(['Survived'], axis=1)
titanic_train_df_v12_X_train.head()

In [ ]:
titanic_train_df_v12_y_train = titanic_train_df_v11['Survived']
titanic_train_df_v12_y_train.head()

In [ ]:
# On the test data also removal of categoricals is needed.
# The following needs to be done on test data
# Remove PassengerID, Name, Ticket and Cabin
tianic_test_df_v2 = tianic_test_df_v1.drop(['Name','Ticket','Cabin'], axis = 1)
tianic_test_df_v2.head()

In [ ]:
#Check if NaN in tianic_test_df_v2
tianic_test_df_v2.isnull().sum()

In [ ]:
# Replace Age NaN with average age
tianic_test_df_v2 = tianic_test_df_v2.fillna(titanic_train_df_v1.mean())
tianic_test_df_v2.head()

In [ ]:
#Check if NaN in tianic_test_df_v2
tianic_test_df_v2.isnull().sum()

In [ ]:
#Now 1-hot encoding for Sex and Embarked
one_hot_features = ['Embarked']
one_hot_encoded = pd.get_dummies(tianic_test_df_v2[one_hot_features],drop_first=True)
one_hot_encoded.head()
# Replacing categorical columns with dummies
tianic_test_df_v3 = tianic_test_df_v2.drop(one_hot_features,axis=1)
tianic_test_df_v3 = pd.concat([tianic_test_df_v2, one_hot_encoded] ,axis=1)
tianic_test_df_v3.head()

one_hot_features = ['Sex']
one_hot_encoded = pd.get_dummies(tianic_test_df_v3[one_hot_features],drop_first=True)
one_hot_encoded.head()
# Replacing categorical columns with dummies
tianic_test_df_v4 = tianic_test_df_v3.drop(one_hot_features,axis=1)
tianic_test_df_v4 = pd.concat([tianic_test_df_v3, one_hot_encoded] ,axis=1)
tianic_test_df_v4.head()

In [ ]:
#Drop Embarked and Sex columns
tianic_test_df_v5 = tianic_test_df_v4.drop(['Embarked','Sex'], axis = 1)
tianic_test_df_v5.head()

In [ ]:
#Normalize age and Fare
#Now make age and Fare and Age normalized.
tianic_test_df_v5['Fare']=(tianic_test_df_v5['Fare']-tianic_test_df_v5['Fare'].mean())/tianic_test_df_v5['Fare'].std()
tianic_test_df_v5['Age']=(tianic_test_df_v5['Age']-tianic_test_df_v5['Age'].mean())/tianic_test_df_v5['Age'].std()

In [ ]:
#Build the Random Forest of Trees model
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=40, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, n_estimators=18,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
rf_clf.fit(titanic_train_df_v12_X_train, titanic_train_df_v12_y_train)

In [ ]:
#Run on training data
tianic_test_df_v5.shape

y_pred = rf_clf.predict(tianic_test_df_v5)

In [ ]:
#Get submission ready
#Create a  DataFrame with the passengers ids and our prediction regarding whether they survived or not
#submission = tianic_test_df_v5['PassengerId'] + y_pred
submission = pd.DataFrame({'PassengerId':tianic_test_df_v5['PassengerId'],'Survived':y_pred})
#Visualize the first 5 rows
submission.head()

In [ ]:
#Convert DataFrame to a csv file that can be uploaded
#This is saved in the same directory as your notebook
filename = 'Titanic Predictions 3.csv'

submission.to_csv(filename,index=False)

print('Saved file: ' + filename)